/* eslint-disable */
/** 
  * THIS FILE IS AUTOGENERATED, DO NOT EDIT IT!
  *
  * instead, edit one of the `.graphql` files in this project and run 
  * `pnpm generate` for this file to be re-created 
*/

import * as Types from '../types/generated';

import { api } from 'api';
export type NoQueriesQueryVariables = Types.Exact<{ [key: string]: never; }>;


export type NoQueriesQuery = { __typename?: 'query_root', no_queries_available: string };


export const NoQueriesDocument = `
    query NoQueries {
  no_queries_available
}
    `;

const injectedRtkApi = api.injectEndpoints({
  endpoints: (build) => ({
    NoQueries: build.query<NoQueriesQuery, NoQueriesQueryVariables | void>({
      query: (variables) => ({ document: NoQueriesDocument, variables })
    }),
  }),
});

export { injectedRtkApi as api };
export const { useNoQueriesQuery, useLazyNoQueriesQuery } = injectedRtkApi;

